# Taps - Brew
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"

# Taps - Others
tap "dart-lang/dart"
tap "github/gh"
tap "hacker1024/hacker1024"
tap "sass/sass"

# Utilities
brew "coreutils"
brew "mas"
brew "xclip"
brew "python@3.9"
brew "gnutls"
brew "libheif"
brew "starship"
brew "sass/sass/sass"
brew "mosh"
brew "psutils"
brew "sampler"
brew "nghttp2"
brew "zstd"
brew "unbound"
brew "srt"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "libusbmuxd"
brew "libimobiledevice"
brew "libpq"

# Programs - user utils
brew "node"
brew "curl"
brew "ffmpeg"
brew "gh"
brew "htop"
brew "micro"
brew "nnn"
brew "midnight-commander"
brew "neofetch"
brew "youtube-dl"
brew "ssh-copy-id"
brew "wget"
brew "imagemagick"
brew "sox"
brew "boom-completion"

# Fonts
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"

# Apps
cask "iterm2"
cask "tiles"
cask "alfred"
cask "whatsapp"
cask "the-unarchiver"
cask "google-chrome"
cask "discord"
cask "github"
cask "inkscape"
cask "notion"
cask "plex"
cask "plexamp"
cask "powershell"
cask "raspberry-pi-imager"
cask "visual-studio-code-insiders"
cask "appcleaner"
cask "coconutbattery"
cask "iina"
cask "mpv"
cask "logitech-options"
cask "monitorcontrol"
cask "zoom"
cask "xcodes"
cask "fliqlo"
cask "handbrake"
cask "hiddenbar"
cask "blender"
cask "pycharm"
cask "intellij-idea"

# appstore stuff
mas "Step Two", id: 1448916662
mas "Keynote", id: 409183694
mas "Pages", id: 409201541
mas "Tab Suspender", id: 1495356253
mas "GoodNotes", id: 1444383602
mas "Paste", id: 967805235
mas "Canary Mail", id: 1236045954

# dreaded xcode
mas "Xcode", id: 497799835
