eval "$(starship init zsh)"

# Shortcuts
alias upgrade="brew update;brew outdated;brew upgrade"

# Clear aliases
alias clear="clear && printf '\e[3J'"
alias c="clear && printf '\e[3J'"
alias cl="clear && printf '\e[3J'"
alias cle="clear && printf '\e[3J'"
alias clea="clear && printf '\e[3J'"

# Sudo aliases
alias s='sudo'

# Auto-sudo applications
alias mc='sudo mc'
alias sm='sudo micro'
alias m='micro'
alias pipupgrade="s -H pip_upgrade_outdated -3 -p"

# ZSH PLUGINS
source $HOMEBREW_PREFIX/opt/zsh-fast-syntax-highlighting/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# MISC
alias zshrc="sudo micro .zshrc"
export PATH="/usr/local/sbin:$PATH"
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
export EDITOR='micro'
export VISUAL='micro'

export LC_ALL=en_SG.UTF-8
export LANG=en_SG.UTF-8
export LANGUAGE=en_SG.UTF-8
