eval "$(starship init zsh)"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install

# Clear aliases
alias clear="clear && printf '\e[3J'"
alias c="clear && printf '\e[3J'"
alias cl="clear && printf '\e[3J'"
alias cle="clear && printf '\e[3J'"
alias clea="clear && printf '\e[3J'"

# Sudo aliases
alias please='sudo'
alias s='sudo'
alias sd='sudo'
alias sud='sudo'

#  applications
alias mc='sudo mc'
alias micro='sudo micro'
alias sn='sudo micro'
alias sm='sudo micro'
alias m='micro'
alias ch='sudo chmod'
alias fastchmod='sudo chmod -R 777'
alias fc='sudo chmod -R 777'
alias upgrade="sudo apt update;sudo apt upgrade"
alias pip="pip3"
alias python='python3'
alias "install"="sudo apt install"
alias zshrc='micro .zshrc'
alias q="qobuz-dl dl"
alias "config"="micro /etc/flexget/config.yml"

# Zsh Plugins
source /usr/share/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source /usr/share/zsh-sudo/sudo.plugin.zsh


# exports?
export EDITOR='micro'
export VISUAL='micro'
